using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client.Silicons.Laws.LawUploadUi;

[GenerateTypedNameReferences]

public sealed partial class LawUploadUi : FancyWindow
{
    public LawUploadUi()
    {
        RobustXamlLoader.Load(this);
    }
}
