using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Silicons.Laws.Modules.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LawEditingWindow : DefaultWindow
    {

        public event Action<string>? OnLawChanged;

        private bool _focused;
        private string _law = string.Empty;

        public LawEditingWindow()
        {
            RobustXamlLoader.Load(this);

            LawLineEdit.OnTextEntered += e =>
            {
                _law = e.Text;
                OnLawChanged?.Invoke(_law);
            };

            LawLineEdit.OnFocusEnter += _ => _focused = true;
            LawLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                LawLineEdit.Text = _law;
            };
        }

        public void SetCurrentLaw(string law)
        {
            LawLineEdit.Text = law;
        }
    }
}
