using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Silicons.Laws.Modules.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LawEditingWindow : DefaultWindow
    {

        public event Action<string>? OnLawChanged;

        public LawEditingWindow()
        {
            RobustXamlLoader.Load(this);

            LawLineEdit.OnTextEntered += e => OnLawChanged?.Invoke(e.Text);
            LawLineEdit.OnFocusExit += e => OnLawChanged?.Invoke(e.Text);
        }

        public void SetCurrentLaw(string law)
        {
            LawLineEdit.Text = law;
        }
    }
}
